version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db.sqlite3  # Persist SQLite database
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=dev_secret_key_change_in_production

volumes:
  sqlite_data: